### ISSUE TITLE
重新佈署後無法輸入中文 都是英文字

### ISSUE THREAD

**Issue by changchichung** [andy0130tw/iridium-bpmf#1]
我依照說明 git clone 之後
建立 link
然後重新佈署rime
也試著重新啟動 fcitx
但是切換到 rime 之後，按鍵就都是直接輸出英文字，而不是注音
請問我還要注意什麼地方？

這是我的 default.custom.yaml
```
cat default.custom.yaml 
patch:
  # 1.
  schema_list:
    - schema: iridium_bpmf
    # add more here

  # 2.
  key_binder/bindings:
    # menu navigation keys
    # these bindings are for HORIZONTAL layout, you may need to modify
    # according to your preferred layout
    - { when: has_menu, accept: Up, send: Page_Up }
    - { when: has_menu, accept: Down, send: Page_Down }
    - { when: has_menu, accept: Left, send: Up }
    - { when: has_menu, accept: Right, send: Down }

  # 3.
  switcher/option_list_separator: ' / '
  switcher/save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
```
就直接從 default.custom.yaml.ref 複製出來到 ~/.config/fcitx/rime/default.custom.yaml，沒有修改

**Comment by changchichung** [comment]
怪了，要先按一次右邊的shift才可以正常輸入中文..

**Comment by changchichung** [comment]
請問要怎麼修改每次重開機後，切換到rime都要先按一次右邊的shift才能開始打字的問題？

**Comment by changchichung** [comment]
找到了，修改  iridium_bpmf.schema.yaml
找到這段
```
switches:
  - name: ascii_mode
    state: [ '中文', '英數' ]
    reset: 1
```
把```reset: 1``` 改成 ```reset: 0```
然後重新佈署就可以了
